CREATE TABLE IF NOT EXISTS intl_market.gb_bess_assets (
    asset                   TEXT NOT NULL,
    valid_from              DATE NOT NULL,
    valid_to                DATE,
    history_table           TEXT,
    value                   TEXT,
    weighting               TEXT,
    postcode                TEXT,
    latitude                DOUBLE PRECISION,
    longitude               DOUBLE PRECISION,
    gsp                     TEXT,
    voltage_kv              NUMERIC,
    import_capacity_mw      NUMERIC,
    export_capacity_mw      NUMERIC,
    import_mpan             TEXT,
    export_mpan             TEXT,
    import_tariff           TEXT,
    export_tariff           TEXT,
    transmission_connected  BOOLEAN,
    transmission_zone       TEXT,
    commissioning_date      DATE,
    tech_type               TEXT,
    is_co_located           BOOLEAN,
    co_located_type         TEXT,
    integrator              TEXT,
    developer               TEXT,
    manufacturer            TEXT,
    is_bmu_flag             BOOLEAN,
    dno                     TEXT,
    ingested_at             TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (asset, valid_from, history_table)
);
